import 'package:darkak_e_commerce_app/core/app_data.dart';
import 'package:darkak_e_commerce_app/models/product_model.dart';
import 'package:darkak_e_commerce_app/models/product_review_model.dart';

List<ProductModel> demoProductList = [
  ProductModel(
      productID: '1',
      productImagePath: watchImage,
      productName: 'Saree',
      productPrice: 400,
      productDescription:
      'Nike Dri-FIT is a polyester fabric designed to help you keep dry so you can more comfortably work harder, longer.',
      imagesPath: List.generate(4, (index) => watchImage),
      color: ['Red', 'Blue', 'Black', 'Orange'],
      attributes: ['S', 'M', 'L', 'XL', 'XXL'],
      customerReviews: ProductReviewModel.productReviewList,
      discounts: 10,
      productRating: 4.5),
  ProductModel(
      productID: '2',
      productImagePath: watchImage,
      productName: 'T-Shirt',
      productPrice: 500,
      productDescription:
      'Nike Dri-FIT is a polyester fabric designed to help you keep dry so you can more comfortably work harder, longer.',
      imagesPath: List.generate(4, (index) => watchImage),
      color: ['Red', 'Blue', 'Black', 'Orange'],
      attributes: ['S', 'M', 'L', 'XL', 'XXL'],
      customerReviews: ProductReviewModel.productReviewList,
      discounts: 10,
      productRating: 4.5),
  ProductModel(
      productID: '3',
      productImagePath: watchImage,
      productName: 'Pant',
      productPrice: 600,
      productDescription:
      'Nike Dri-FIT is a polyester fabric designed to help you keep dry so you can more comfortably work harder, longer.',
      imagesPath: List.generate(4, (index) => watchImage),
      color: ['Red', 'Blue', 'Black', 'Orange'],
      attributes: ['S', 'M', 'L', 'XL', 'XXL'],
      customerReviews: ProductReviewModel.productReviewList,
      discounts: 10,
      productRating: 4.5),
  ProductModel(
      productID: '1',
      productImagePath: watchImage,
      productName: 'Saree',
      productPrice: 400,
      productDescription:
      'Nike Dri-FIT is a polyester fabric designed to help you keep dry so you can more comfortably work harder, longer.',
      imagesPath: List.generate(4, (index) => watchImage),
      color: ['Red', 'Blue', 'Black', 'Orange'],
      attributes: ['S', 'M', 'L', 'XL', 'XXL'],
      customerReviews: ProductReviewModel.productReviewList,
      discounts: 10,
      productRating: 4.5),
  ProductModel(
      productID: '2',
      productImagePath: watchImage,
      productName: 'T-Shirt',
      productPrice: 500,
      productDescription:
      'Nike Dri-FIT is a polyester fabric designed to help you keep dry so you can more comfortably work harder, longer.',
      imagesPath: List.generate(4, (index) => watchImage),
      color: ['Red', 'Blue', 'Black', 'Orange'],
      attributes: ['S', 'M', 'L', 'XL', 'XXL'],
      customerReviews: ProductReviewModel.productReviewList,
      discounts: 10,
      productRating: 4.5),
  ProductModel(
      productID: '3',
      productImagePath: watchImage,
      productName: 'Pant',
      productPrice: 600,
      productDescription:
      'Nike Dri-FIT is a polyester fabric designed to help you keep dry so you can more comfortably work harder, longer.',
      imagesPath: List.generate(4, (index) => watchImage),
      color: ['Red', 'Blue', 'Black', 'Orange'],
      attributes: ['S', 'M', 'L', 'XL', 'XXL'],
      customerReviews: ProductReviewModel.productReviewList,
      discounts: 10,
      productRating: 4.5),
  ProductModel(
      productID: '1',
      productImagePath: watchImage,
      productName: 'Saree',
      productPrice: 400,
      productDescription:
      'Nike Dri-FIT is a polyester fabric designed to help you keep dry so you can more comfortably work harder, longer.',
      imagesPath: List.generate(4, (index) => watchImage),
      color: ['Red', 'Blue', 'Black', 'Orange'],
      attributes: ['S', 'M', 'L', 'XL', 'XXL'],
      customerReviews: ProductReviewModel.productReviewList,
      discounts: 10,
      productRating: 4.5),
  ProductModel(
      productID: '2',
      productImagePath: watchImage,
      productName: 'T-Shirt',
      productPrice: 500,
      productDescription:
      'Nike Dri-FIT is a polyester fabric designed to help you keep dry so you can more comfortably work harder, longer.',
      imagesPath: List.generate(4, (index) => watchImage),
      color: ['Red', 'Blue', 'Black', 'Orange'],
      attributes: ['S', 'M', 'L', 'XL', 'XXL'],
      customerReviews: ProductReviewModel.productReviewList,
      discounts: 10,
      productRating: 4.5),
  ProductModel(
      productID: '3',
      productImagePath: watchImage,
      productName: 'Pant',
      productPrice: 600,
      productDescription:
      'Nike Dri-FIT is a polyester fabric designed to help you keep dry so you can more comfortably work harder, longer.',
      imagesPath: List.generate(4, (index) => watchImage),
      color: ['Red', 'Blue', 'Black', 'Orange'],
      attributes: ['S', 'M', 'L', 'XL', 'XXL'],
      customerReviews: ProductReviewModel.productReviewList,
      discounts: 10,
      productRating: 4.5),
  ProductModel(
      productID: '1',
      productImagePath: watchImage,
      productName: 'Saree',
      productPrice: 400,
      productDescription:
      'Nike Dri-FIT is a polyester fabric designed to help you keep dry so you can more comfortably work harder, longer.',
      imagesPath: List.generate(4, (index) => watchImage),
      color: ['Red', 'Blue', 'Black', 'Orange'],
      attributes: ['S', 'M', 'L', 'XL', 'XXL'],
      customerReviews: ProductReviewModel.productReviewList,
      discounts: 10,
      productRating: 4.5),
  ProductModel(
      productID: '2',
      productImagePath: watchImage,
      productName: 'T-Shirt',
      productPrice: 500,
      productDescription:
      'Nike Dri-FIT is a polyester fabric designed to help you keep dry so you can more comfortably work harder, longer.',
      imagesPath: List.generate(4, (index) => watchImage),
      color: ['Red', 'Blue', 'Black', 'Orange'],
      attributes: ['S', 'M', 'L', 'XL', 'XXL'],
      customerReviews: ProductReviewModel.productReviewList,
      discounts: 10,
      productRating: 4.5),
  ProductModel(
      productID: '3',
      productImagePath: watchImage,
      productName: 'Pant',
      productPrice: 600,
      productDescription:
      'Nike Dri-FIT is a polyester fabric designed to help you keep dry so you can more comfortably work harder, longer.',
      imagesPath: List.generate(4, (index) => watchImage),
      color: ['Red', 'Blue', 'Black', 'Orange'],
      attributes: ['S', 'M', 'L', 'XL', 'XXL'],
      customerReviews: ProductReviewModel.productReviewList,
      discounts: 10,
      productRating: 4.5),
  ProductModel(
      productID: '1',
      productImagePath: watchImage,
      productName: 'Saree',
      productPrice: 400,
      productDescription:
      'Nike Dri-FIT is a polyester fabric designed to help you keep dry so you can more comfortably work harder, longer.',
      imagesPath: List.generate(4, (index) => watchImage),
      color: ['Red', 'Blue', 'Black', 'Orange'],
      attributes: ['S', 'M', 'L', 'XL', 'XXL'],
      customerReviews: ProductReviewModel.productReviewList,
      discounts: 10,
      productRating: 4.5),
  ProductModel(
      productID: '2',
      productImagePath: watchImage,
      productName: 'T-Shirt',
      productPrice: 500,
      productDescription:
      'Nike Dri-FIT is a polyester fabric designed to help you keep dry so you can more comfortably work harder, longer.',
      imagesPath: List.generate(4, (index) => watchImage),
      color: ['Red', 'Blue', 'Black', 'Orange'],
      attributes: ['S', 'M', 'L', 'XL', 'XXL'],
      customerReviews: ProductReviewModel.productReviewList,
      discounts: 10,
      productRating: 4.5),
  ProductModel(
      productID: '3',
      productImagePath: watchImage,
      productName: 'Pant',
      productPrice: 600,
      productDescription:
      'Nike Dri-FIT is a polyester fabric designed to help you keep dry so you can more comfortably work harder, longer.',
      imagesPath: List.generate(4, (index) => watchImage),
      color: ['Red', 'Blue', 'Black', 'Orange'],
      attributes: ['S', 'M', 'L', 'XL', 'XXL'],
      customerReviews: ProductReviewModel.productReviewList,
      discounts: 10,
      productRating: 4.5),
  ProductModel(
      productID: '1',
      productImagePath: watchImage,
      productName: 'Saree',
      productPrice: 400,
      productDescription:
      'Nike Dri-FIT is a polyester fabric designed to help you keep dry so you can more comfortably work harder, longer.',
      imagesPath: List.generate(4, (index) => watchImage),
      color: ['Red', 'Blue', 'Black', 'Orange'],
      attributes: ['S', 'M', 'L', 'XL', 'XXL'],
      customerReviews: ProductReviewModel.productReviewList,
      discounts: 10,
      productRating: 4.5),
  ProductModel(
      productID: '2',
      productImagePath: watchImage,
      productName: 'T-Shirt',
      productPrice: 500,
      productDescription:
      'Nike Dri-FIT is a polyester fabric designed to help you keep dry so you can more comfortably work harder, longer.',
      imagesPath: List.generate(4, (index) => watchImage),
      color: ['Red', 'Blue', 'Black', 'Orange'],
      attributes: ['S', 'M', 'L', 'XL', 'XXL'],
      customerReviews: ProductReviewModel.productReviewList,
      discounts: 10,
      productRating: 4.5),
  ProductModel(
      productID: '3',
      productImagePath: watchImage,
      productName: 'Pant',
      productPrice: 600,
      productDescription:
      'Nike Dri-FIT is a polyester fabric designed to help you keep dry so you can more comfortably work harder, longer.',
      imagesPath: List.generate(4, (index) => watchImage),
      color: ['Red', 'Blue', 'Black', 'Orange'],
      attributes: ['S', 'M', 'L', 'XL', 'XXL'],
      customerReviews: ProductReviewModel.productReviewList,
      discounts: 10,
      productRating: 4.5),
  ProductModel(
      productID: '1',
      productImagePath: watchImage,
      productName: 'Saree',
      productPrice: 400,
      productDescription:
      'Nike Dri-FIT is a polyester fabric designed to help you keep dry so you can more comfortably work harder, longer.',
      imagesPath: List.generate(4, (index) => watchImage),
      color: ['Red', 'Blue', 'Black', 'Orange'],
      attributes: ['S', 'M', 'L', 'XL', 'XXL'],
      customerReviews: ProductReviewModel.productReviewList,
      discounts: 10,
      productRating: 4.5),
  ProductModel(
      productID: '2',
      productImagePath: watchImage,
      productName: 'T-Shirt',
      productPrice: 500,
      productDescription:
      'Nike Dri-FIT is a polyester fabric designed to help you keep dry so you can more comfortably work harder, longer.',
      imagesPath: List.generate(4, (index) => watchImage),
      color: ['Red', 'Blue', 'Black', 'Orange'],
      attributes: ['S', 'M', 'L', 'XL', 'XXL'],
      customerReviews: ProductReviewModel.productReviewList,
      discounts: 10,
      productRating: 4.5),
  ProductModel(
      productID: '3',
      productImagePath: watchImage,
      productName: 'Pant',
      productPrice: 600,
      productDescription:
      'Nike Dri-FIT is a polyester fabric designed to help you keep dry so you can more comfortably work harder, longer.',
      imagesPath: List.generate(4, (index) => watchImage),
      color: ['Red', 'Blue', 'Black', 'Orange'],
      attributes: ['S', 'M', 'L', 'XL', 'XXL'],
      customerReviews: ProductReviewModel.productReviewList,
      discounts: 10,
      productRating: 4.5),
];